### ISSUE TITLE
@extend does not work with :not() directive

### ISSUE THREAD

**Issue by qsm-odoo** [sass/libsass-python#269]
This code:
```scss
.c {
    color: blue;
}
.a > .b:not(.c) {
    color: green;
}
.d > .b {
    @extend .c;
}
```
compiles to
```css
.c, .d > .b {
    color: blue;
}
.a > .b:not(.c):not(.d > .b) {
    color: green;
}
```
while it should have been: (as I get using the sass command directly)
```css
.c, .d > .b {
    color: blue;
}
.a > .b:not(.c) {
    color: green;
}
```
This error makes browsers completely ignore the green color rule as `:not(.d > .b)` is not a valid css selector.
